
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      service: front
  template:
    metadata:
      name: front
      labels:
        name: front
        app: front
        service: front
    spec:
      containers:
      - image: chaostoolkit/front
        name: front
        ports:
        - containerPort: 8000
          protocol: TCP
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "200m"
            memory: 64Mi
          requests:
            cpu: "100m"
            memory: 64Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: middle
spec:
  replicas: 1
  selector:
    matchLabels:
      service: middle
  template:
    metadata:
      name: middle
      labels:
        name: middle
        app: middle
        service: middle
    spec:
      containers:
      - image: chaostoolkit/middle
        name: middle
        command: ["sh"]
        # fake a slow app
        args: ["-c", "sleep 10s; uvicorn --host 0.0.0.0 --port 8001 app:app"]
        ports:
        - containerPort: 8001
          protocol: TCP
          name: http
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 12
          periodSeconds: 5
        resources:
          limits:
            cpu: "200m"
            memory: 64Mi
          requests:
            cpu: "100m"
            memory: 64Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: back
spec:
  replicas: 1
  selector:
    matchLabels:
      service: back
  template:
    metadata:
      name: back
      labels:
        name: back
        app: back
        service: back
    spec:
      containers:
      - image: chaostoolkit/back
        name: back
        ports:
        - containerPort: 8002
          protocol: TCP
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "200m"
            memory: 64Mi
          requests:
            cpu: "100m"
            memory: 64Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

---
kind: Service
apiVersion: v1
metadata:
  name: front
  labels:
    service: front
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    service: front

---
kind: Service
apiVersion: v1
metadata:
  name: middle
  labels:
    service: middle
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8001
    targetPort: 8001
  selector:
    service: middle

---
kind: Service
apiVersion: v1
metadata:
  name: back
  labels:
    service: back
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8002
    targetPort: 8002
  selector:
    service: back

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ratelimit
spec:
  rateLimit:
      average: 300
      burst: 100

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: httpmiddlewares
spec:
  chain:
    middlewares:
    - name: ratelimit

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: front-http
spec:
  entryPoints:
    - http
  routes:
  - match: PathPrefix(`/`)
    kind: Rule
    middlewares:
    - name: httpmiddlewares
    services:
    - name: front
      port: 8000

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: front
  labels:
    app: front
spec:
  jobLabel: front
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      service: front
  endpoints:
  - port: http
    path: /metrics
    scheme: http
    interval: 10s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: middle
  labels:
    app: middle
spec:
  jobLabel: middle
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      service: middle
  endpoints:
  - port: http
    path: /metrics
    scheme: http
    interval: 10s